kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bahnvision-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Ingress HTTP port mapping
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # Ingress HTTPS port mapping
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # Additional ports for services
  - containerPort: 3000
    hostPort: 3000
    protocol: TCP
  - containerPort: 8000
    hostPort: 8000
    protocol: TCP